
name: Actualización Diaria de Datos

on:
  schedule:
    - cron: "0 6 * * *"  # Ejecutar todos los días a las 6:00 AM UTC
  workflow_dispatch:      # Permitir ejecución manual

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: "4.3.0"
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libpoppler-cpp-dev
        
    - name: Install R dependencies
      run: |
        R -e "install.packages(c('Tivy', 'dplyr', 'leaflet', 'pdftools'))"
        
    - name: Run daily update
      run: Rscript actualizacion_diaria.R
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        git diff --staged --quiet || git commit -m "Actualización automática de datos - $(date)"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

